### PR TITLE
spi: accept bitOrder in lowercase

### LINKED ISSUE #125: SPI bitOrder value
When specifying a `bitValue` of `'msb'` (which is the default) the tessel throws an error at me.

```javascript
this.spi = new port.SPI({
  clockSpeed: 4*1E6,
  cpol: 0,
  cpha: 0,
  bitOrder: 'msb',
  chipSelect: this.CS,
  chipSelectActive: 'low'
});
```

```text
Error: Invalid property value
    at _new ([string "colony-init.lua"]:1)
    at propertySetWithDefault ([string "tessel.js"]:49)
    at f ([string "tessel.js"]:1183)
    at _new ([string "colony-init.lua"]:1)
    at f ([string "tessel.js"]:1425)
    at _new ([string "colony-init.lua"]:1)
    at f (/app//index.js:34)
    at _new ([string "colony-init.lua"]:1)
    at use (/app//index.js:78)
    at res (/app/test.js:5)
```

Removing just `bitOrder: 'msb',` fixes it...

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #125

### CODE REVIEW

**Comment by jiahuang** [comment]
Is it better to have multiple keys defined as the same thing or just do a `.toLowerCase` cast in the function that finds the keys? Personally I'd prefer the `.toLowerCase` cast. It would also handle these kinds of situations in the future.

**Comment by jiahuang** [comment]
Err, I guess in this case it would be `.toUpperCase`

**Comment by LinusU** [comment]
That wouldn't work when passed `Number`s though... Although I guess that when accessing a property on a object the number is converted to a string anyhow...

Maybe this
```javascript
if (typeof provided === 'undefined') { return defaultProp; }

var key = String(provided).toLowerCase();

if (possibility.hasOwnProperty(key) === false) {
  throw new Error('Invalid property value: ' + key);
}

return possibility[key];
```

I also switched to `hasOwnProperty` since otherwise `'valueOf'` will be a valid `bitOrder`.

**Comment by LinusU** [comment]
@jiahuang I updated to use the code i suggested, I couldn't test it though as I think it requires connecting some modules to the tessel to the right ports, and bridging some IO...

**Comment by tm-rampart** [comment]
Approved by @jiahuang. [Running tests](https://rampart.tessel.io/jobs/5914).

**Pull request merged**
